### PR TITLE
Manage IPsec rules

### PR DESCRIPTION
**Pull request by webalexeu**
I've started to add the management of IPsec rules within the module.
@GeoffWilliams, I'm currently looking to rewrite the all module to have only one script to perform everything but based on get-netfirewallrules and not netsh (already the case for ipsec rules)
Are you interested or do you prefer to keep your module dedicated with netsh ?

### CODE REVIEW

**Comment by GeoffWilliams** [comment]
@webalexeu Just as background `netsh` was used because I was trying to automate some of the hardening guides out there that explicitly used `netsh` to turn things like file sharing and RDP on/off. No-doubt things have moved on since this was written and the `netsh` approach leads to bugs like https://github.com/GeoffWilliams/puppet-windows_firewall/issues/14 that have no easy fix other then a rewrite to make the equivalent calls in PowerShell.

I like the approach you've taken and I would have probably coded something similar if I was to attempt this myself.

I'm not actively working on Puppet at the moment and while I'm happy to review small changes like the other two PRs, I'm not in a position to add big new features like this. Are you interested in taking over maintenance of this module? Otherwise a separate module dealing with IPSec might be the way to go.

**Comment by webalexeu** [comment]
Yes, I'm interested. I was thinking to have one module to manage all the features possible in Windows Firewall.
Moving away from netsh has a lot of advantages I think and will be easier to maintain. The only backward issue can be performance for environment where the rules are not flushed (To be confirmed)

**Comment by webalexeu** [comment]
I still need to write the acceptance checks for this merge request

**Comment by GeoffWilliams** [comment]
Cool! well what I'd suggest is you publish your updated module to github and then the forge. Once that's done we deprecate this module on the forge and direct people to your new version. 

BTW the acceptance testing system at the moment is PDQTest which also is no longer maintained - I was about to create a new framework for more general testing but haven't got around to it yet. I think the Puppet are recommending litmus these days so you might also want to switch over to that. 

I also had performance problems munging rules in PowerShell which is why the script for regular rules tries to use `netsh` as much as possible. There's a stackoverflow on my own timing observations if it helps: https://stackoverflow.com/questions/53146884/how-can-i-speed-up-powershell-to-get-firewall-rules-on-windows-10

**Comment by webalexeu** [comment]
@GeoffWilliams Module published
https://forge.puppet.com/modules/webalex/windows_firewall/0.1.0 

Thank you again for your proposition

**Comment by GeoffWilliams** [comment]
Created FORGE ticket to deprecate my module and recommend yours as alternative: https://tickets.puppetlabs.com/browse/FORGE-578

Thanks for taking over ownership of the module! :beers: 

Now I will close all remaining PRs, tickets and archive this repository.

**Pull request closed without merging**
